//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafýndan oluþturuldu.
//
//     Bu dosyada yapýlacak deðiþiklikler yanlýþ davranýþa neden olabilir ve
//     kod yeniden üretildiðinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarifvakti
{


    public partial class Default
    {
    }
}
